
DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
    email VARCHAR(255) NOT NULL,
    password VARCHAR(60) NOT NULL,
    name VARCHAR(60),
    birthday DATETIME,
    UNIQUE(email)
);

DROP TABLE IF EXISTS loggedOn;
CREATE TABLE IF NOT EXISTS loggedOn (
    idNr INTEGER PRIMARY KEY AUTOINCREMENT,
    time CURRENT_TIMESTAMP,
    email VARCHAR(255),
    UNIQUE(email),
    CONSTRAINT onlyUsers
        FOREIGN KEY(email) 
        REFERENCES users(email)
);

DROP TABLE IF EXISTS depot;
CREATE TABLE IF NOT EXISTS depot (
    idNr INTEGER PRIMARY KEY AUTOINCREMENT,
    time CURRENT_TIMESTAMP,
    sum INT NOT NULL,
    nrProducts INT NOT NULL,
    email VARCHAR(255) NOT NULL,
    CONSTRAINT onlyUsers
        FOREIGN KEY(email) 
        REFERENCES users(email)
);

DROP TABLE IF EXISTS product;
CREATE TABLE IF NOT EXISTS product (
    idNr INTEGER PRIMARY KEY AUTOINCREMENT,
    time CURRENT_TIMESTAMP,
    price INT,
    name VARCHAR(255) NOT NULL,
    UNIQUE(name)
);